FROM adoptopenjdk/openjdk11
WORKDIR /
ADD processPensionMicroservice-0.0.1-SNAPSHOT.jar processPensionMicroservice-0.0.1-SNAPSHOT.jar
EXPOSE 8081
CMD java -jar processPensionMicroservice-0.0.1-SNAPSHOT.jar