FROM adoptopenjdk/openjdk11
WORKDIR /
ADD pensionerDisbursementMicroservice-0.0.1-SNAPSHOT.jar pensionerDisbursementMicroservice-0.0.1-SNAPSHOT.jar
EXPOSE 8083
CMD java -jar pensionerDisbursementMicroservice-0.0.1-SNAPSHOT.jar