FROM adoptopenjdk/openjdk11
WORKDIR /
ADD pensionerDetailsMicroservice-0.0.1-SNAPSHOT.jar pensionerDetailsMicroservice-0.0.1-SNAPSHOT.jar
EXPOSE 8082
CMD java -jar pensionerDetailsMicroservice-0.0.1-SNAPSHOT.jar